name: Build Windows Release
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  create:
    tags:
      - 'v*'
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qt5compat qtmultimedia'
        cache: true

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd build
        nmake

    - name: Deploy Qt dependencies
      run: |
        cd build
        windeployqt.exe SQL_LOGIN.exe --release --no-translations

    - name: Download MySQL plugin and dependencies
      shell: pwsh
      run: |
        Write-Host "Downloading MySQL plugin for Qt 6.10.0 MSVC2022..."
        $pluginUrl = "https://github.com/thecodemonkey86/qt_mysql_driver/releases/download/qmysql_6.10.0/qsqlmysql.dll_Qt_SQL_driver_6.10.0_MSVC2022_64-bit.zip"
        Invoke-WebRequest -Uri $pluginUrl -OutFile mysql_plugin.zip

        Write-Host "Extracting plugin..."
        Expand-Archive mysql_plugin.zip -DestinationPath mysql_temp -Force

        Write-Host "Creating sqldrivers directory..."
        New-Item -ItemType Directory -Force -Path "build/sqldrivers"

        Write-Host "Copying qsqlmysql.dll..."
        $dllPath = Get-ChildItem -Path mysql_temp -Filter "qsqlmysql.dll" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($dllPath) {
          Copy-Item $dllPath.FullName -Destination "build/sqldrivers/qsqlmysql.dll"
          Write-Host "SUCCESS: qsqlmysql.dll copied"
        }

        Write-Host "`nDownloading libmysql.dll from alternative sources..."
        $libmysqlCopied = $false

        # Intento 1: WinLibs mirror
        if (-not $libmysqlCopied) {
          try {
            Write-Host "Trying WinLibs mirror..."
            $libmysqlUrl = "https://github.com/winlibs/libmysql/releases/download/v8.0.31/libmysql-8.0.31-winx64.zip"
            Invoke-WebRequest -Uri $libmysqlUrl -OutFile libmysql.zip -ErrorAction Stop -TimeoutSec 60

            Expand-Archive libmysql.zip -DestinationPath libmysql_temp -Force

            $libmysqlPath = Get-ChildItem -Path libmysql_temp -Filter "libmysql.dll" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
            if ($libmysqlPath) {
              Copy-Item $libmysqlPath.FullName -Destination "build/libmysql.dll"
              Write-Host "SUCCESS: libmysql.dll copied from WinLibs"
              $libmysqlCopied = $true
            }
          } catch {
            Write-Host "WinLibs mirror failed: $($_.Exception.Message)"
          }
        }

        # Intento 2: MySQL CDN
        if (-not $libmysqlCopied) {
          try {
            Write-Host "Trying MySQL CDN..."
            $cdnUrl = "https://cdn.mysql.com/Downloads/Connector-C/mysql-connector-c-6.1.11-winx64.zip"
            Invoke-WebRequest -Uri $cdnUrl -OutFile mysql_connector.zip -TimeoutSec 120 -ErrorAction Stop

            Expand-Archive mysql_connector.zip -DestinationPath mysql_connector_temp -Force

            $libmysqlPath = Get-ChildItem -Path mysql_connector_temp -Filter "libmysql.dll" -Recurse | Select-Object -First 1
            if ($libmysqlPath) {
              Copy-Item $libmysqlPath.FullName -Destination "build/libmysql.dll"
              Write-Host "SUCCESS: libmysql.dll copied from MySQL CDN"
              $libmysqlCopied = $true
            }
          } catch {
            Write-Host "MySQL CDN failed: $($_.Exception.Message)"
          }
        }

        # Intento 3: Archive.org mirror
        if (-not $libmysqlCopied) {
          try {
            Write-Host "Trying Archive.org mirror..."
            $archiveUrl = "https://archive.org/download/mysql-connector-c-6.1.11-winx64/mysql-connector-c-6.1.11-winx64.zip"
            Invoke-WebRequest -Uri $archiveUrl -OutFile mysql_archive.zip -TimeoutSec 120 -ErrorAction Stop

            Expand-Archive mysql_archive.zip -DestinationPath mysql_archive_temp -Force

            $libmysqlPath = Get-ChildItem -Path mysql_archive_temp -Filter "libmysql.dll" -Recurse | Select-Object -First 1
            if ($libmysqlPath) {
              Copy-Item $libmysqlPath.FullName -Destination "build/libmysql.dll"
              Write-Host "SUCCESS: libmysql.dll copied from Archive.org"
              $libmysqlCopied = $true
            }
          } catch {
            Write-Host "Archive.org mirror failed: $($_.Exception.Message)"
          }
        }

        if (-not $libmysqlCopied) {
          Write-Host "WARNING: Could not download libmysql.dll from any source"
          Write-Host "The application may not work without this file"
        }

        Write-Host "`nMySQL setup completed"

    - name: Verify MySQL plugin
      shell: pwsh
      run: |
        Write-Host "`n=== Verification ==="
        Write-Host "Contents of build/ (DLLs only):"
        Get-ChildItem "build" -Filter "*.dll" | Format-Table Name, Length

        Write-Host "`nContents of build/sqldrivers/:"
        if (Test-Path "build/sqldrivers") {
          Get-ChildItem "build/sqldrivers" -Recurse | Format-Table Name, Length
        } else {
          Write-Host "ERROR: sqldrivers directory not found!"
        }

        $errors = @()

        if (Test-Path "build/sqldrivers/qsqlmysql.dll") {
          Write-Host "`nSUCCESS: qsqlmysql.dll is present"
        } else {
          Write-Host "`nERROR: qsqlmysql.dll NOT FOUND!"
          $errors += "qsqlmysql.dll missing"
        }

        if (Test-Path "build/libmysql.dll") {
          Write-Host "SUCCESS: libmysql.dll is present"
        } else {
          Write-Host "WARNING: libmysql.dll NOT FOUND"
          $errors += "libmysql.dll missing"
        }

        if ($errors.Count -gt 0) {
          Write-Host "`nErrors found: $($errors -join ', ')"
          if ($errors -contains "qsqlmysql.dll missing") {
            exit 1
          }
        }

    - name: Create README
      shell: pwsh
      run: |
        $content = "Sistema de Ventas - Windows Portable`n"
        $content += "======================================`n`n"
        $content += "REQUISITOS:`n"
        $content += "- Windows 10 o superior (64-bit)`n"
        $content += "- Conexion a Internet`n`n"
        $content += "INSTRUCCIONES:`n"
        $content += "1. Extraer el ZIP completo`n"
        $content += "2. Ejecutar SQL_LOGIN.exe o Ejecutar.bat`n"
        $content += "3. Ingresar credenciales`n`n"
        $content += "NOTA: No requiere instalacion ni permisos de administrador.`n"
        $content += "Todas las dependencias estan incluidas.`n"
        $content | Out-File -FilePath "build/README.txt" -Encoding UTF8

    - name: Create launcher
      shell: pwsh
      run: |
        $batch = "@echo off`r`n"
        $batch += "title Sistema de Ventas`r`n"
        $batch += "cls`r`n"
        $batch += "echo ========================================`r`n"
        $batch += "echo   Sistema de Ventas`r`n"
        $batch += "echo ========================================`r`n"
        $batch += "echo.`r`n"
        $batch += "echo Iniciando aplicacion...`r`n"
        $batch += "echo.`r`n"
        $batch += "SQL_LOGIN.exe`r`n"
        $batch += "if errorlevel 1 (`r`n"
        $batch += "  echo.`r`n"
        $batch += "  echo ERROR: No se pudo iniciar.`r`n"
        $batch += "  echo Verifique que todas las DLLs esten presentes.`r`n"
        $batch += "  echo.`r`n"
        $batch += "  pause`r`n"
        $batch += ")`r`n"
        $batch | Out-File -FilePath "build/Ejecutar.bat" -Encoding ASCII -NoNewline

    - name: Package portable version
      shell: pwsh
      run: |
        cd build
        Write-Host "Packaging files..."
        $exclude = @('*.cpp', '*.h', '*.obj', 'CMakeFiles', '*.cmake', 'Makefile', 'mysql_temp', 'mysql_connector_temp', 'libmysql_temp', 'mysql_archive_temp')
        Get-ChildItem | Where-Object { $_.Name -notin $exclude -and $_.Name -notlike 'CMake*' } | Compress-Archive -DestinationPath ../SistemaVentas-Windows-Portable.zip -Force
        Write-Host "Package created successfully"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SistemaVentas-Windows
        path: SistemaVentas-Windows-Portable.zip
        retention-days: 90
