name: Build Windows Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  create:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qt5compat qtmultimedia'
        cache: true

    - name: Download MySQL plugin
      shell: pwsh
      run: |
        # Descargar plugin precompilado versión 6.7.3 MSVC2019 64-bit
        Invoke-WebRequest -Uri "https://github.com/thecodemonkey86/qt_mysql_driver/releases/download/qmysql_6.7.3/qsqlmysql.dll_Qt_SQL_driver_6.7.3_MSVC2019_64-bit.zip" -OutFile mysql_plugin.zip
        Expand-Archive mysql_plugin.zip -DestinationPath mysql_temp
        # Copiar a la carpeta build
        New-Item -ItemType Directory -Force -Path "build/sqldrivers"
        Copy-Item "mysql_temp/qsqlmysql.dll" -Destination "build/sqldrivers/" -ErrorAction Continue
        # También copiar libmysql.dll si existe
        if (Test-Path "mysql_temp/libmysql.dll") {
          Copy-Item "mysql_temp/libmysql.dll" -Destination "build/" -ErrorAction Continue
        }
        Write-Host "MySQL plugin setup completed"

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd build
        nmake

    - name: Deploy Qt dependencies
      run: |
        cd build
        windeployqt.exe SQL_LOGIN.exe --release --no-translations

    - name: Create README
      shell: pwsh
      run: |
        $content = "Sistema de Ventas - Windows Portable`n"
        $content += "======================================`n`n"
        $content += "REQUISITOS:`n"
        $content += "- Windows 10 o superior`n"
        $content += "- Conexion a Internet`n`n"
        $content += "INSTRUCCIONES:`n"
        $content += "1. Extraer el ZIP`n"
        $content += "2. Ejecutar SQL_LOGIN.exe`n"
        $content += "3. Ingresar credenciales`n`n"
        $content += "No requiere instalacion ni permisos de administrador.`n"
        $content | Out-File -FilePath "build/README.txt" -Encoding UTF8

    - name: Create launcher
      shell: pwsh
      run: |
        $batch = "@echo off`r`n"
        $batch += "title Sistema de Ventas`r`n"
        $batch += "echo Iniciando...`r`n"
        $batch += "SQL_LOGIN.exe`r`n"
        $batch += "if errorlevel 1 pause`r`n"
        $batch | Out-File -FilePath "build/Ejecutar.bat" -Encoding ASCII -NoNewline

    - name: Package portable version
      shell: pwsh
      run: |
        cd build
        $exclude = @('*.cpp', '*.h', '*.obj', 'CMakeFiles', '*.cmake', 'Makefile')
        Get-ChildItem | Where-Object { $_.Name -notin $exclude -and $_.Name -notlike 'CMake*' } | Compress-Archive -DestinationPath ../SistemaVentas-Windows-Portable.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SistemaVentas-Windows
        path: SistemaVentas-Windows-Portable.zip
        retention-days: 90
